name: flutter_watch
description: A plugin that offers Flutter support for both Wear OS for Android/iOS and WatchOS for iOS.
version: 1.1.0
homepage: https://github.com/fluttercommunity/flutter_wear_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mjohnsullivan.flutterwear.wear
        pluginClass: WearPlugin
